// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// For migrations, use direct connection (required for schema changes)
// Runtime queries use connection pooler (configured in src/lib/db.ts)
const databaseUrl = process.env["PRISMA_POSTGRES_POSTGRES_URL"] || process.env["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error("PRISMA_POSTGRES_POSTGRES_URL or DATABASE_URL must be set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
