// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use PRISMA_POSTGRES_PRISMA_DATABASE_URL in production (Vercel/Prisma Postgres) or DATABASE_URL for local development
const databaseUrl = process.env["PRISMA_POSTGRES_PRISMA_DATABASE_URL"] || process.env["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error("PRISMA_POSTGRES_PRISMA_DATABASE_URL or DATABASE_URL must be set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
